app/__init__.py
from flask import Flask
from app.routes.home import home_bp
from app.short_url_generator import URLShortener
from app.pg_database import PostgreDB

def create_app(config_class=None):
    app = Flask(__name__)
    app.register_blueprint(home_bp)
    
    app.config.from_object(config_class) 
    
    app.url_shortener = URLShortener(length=app.config["SHORT_URL_LENGTH"]) #bind url shortener instance  to app
    app.database = PostgreDB(app.config["DB_CONFIG"]) #bind database instance to app

    return app 

app/main.py
from app import create_app
from config import DevConfig



if __name__ == '__main__':
    app = create_app(DevConfig)
    app.run(host='0.0.0.0', port=app.config['PORT'], debug=app.config['DEBUG'])

app/routes/home.py
from flask import Blueprint, redirect, render_template, request, current_app


home_bp = Blueprint('home', __name__)


@home_bp.route('/', methods=['GET', 'POST'])
def home():
    """
    Home page.

    If accessed via POST request, it shortens the URL and stores it in the database.
    If accessed via GET request, it displays the homepage.

    Returns:
        str: Rendered HTML template.

    Raises:
        None.
    """
    database = current_app.database

    if request.method == 'POST':
        url = request.values['fullUrl'].strip()
        short_url = database.fetch_url_if_exists(original=url)
        if not short_url:
            short_url = current_app.url_shortener.shorten_url(url)
            if not short_url:
                result = 'Validation Failure. This may be an incorrect URL.'
            else:
                database.add_data((short_url, url))
                result = f"{current_app.config["PROTOCOL"]}://{current_app.config["DOMAIN_NAME"]}/{short_url}"
        else:
            result = f"{current_app.config["PROTOCOL"]}://{current_app.config["DOMAIN_NAME"]}/{short_url}"
        return render_template('index.html', result=result)
    else:
        database.create_table()
        return render_template('index.html')


@home_bp.route('/<url>')
def url_redirect(url):
    """
    Redirect to original URL.

    Args:
        url (str): The shortened URL.

    Returns:
        str: Redirection to the original URL if found, otherwise an error message.

    Raises:
        None.
    """
    result = current_app.database.fetch_url_if_exists(shorten=url)
    if result:
        return redirect(result)
    else:
        return 'PAGE DOES NOT EXIST.'



@home_bp.route('/favicon.ico')
def favicon():
    return '', 204 

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>URL Shortener</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css')}}" />
</head>
<body>
    <div class="container">
        <header class="title-container">
            <h1>URL Shortener</h1>
        </header>

        <div class="form-container">
            <form method="post" action="{{ url_for('home.home') }}">
                <label for="fullUrl" class="visually-hidden">Paste URL Here</label>
                <div class="input-group">
                    <input required placeholder="Enter the URL" type="url" name="fullUrl" id="fullUrl">
                    <button class="btn">Shorten</button>
                </div>
            </form>

            <div class="shortUrl">
                <input type="text" name="shortUrl" placeholder="shortened url" id="shortUrl" value="{{ result if result else '' }}" readonly>
            </div>
        </div>
    </div>
</body>
</html>